"""Migracion inicial de la base de datos

Revision ID: 3175faa3ed67
Revises: 
Create Date: 2025-06-23 12:56:40.692039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3175faa3ed67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion',
        sa.Column('id_calificacion', sa.Integer(), nullable=False),
        sa.Column('calificacion', sa.Integer(), nullable=True),
        sa.Column('descripcion', sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_table('categoria',
        sa.Column('id_categoria', sa.Integer(), nullable=False),
        sa.Column('nombre_categoria', sa.String(length=250), nullable=True),
        sa.Column('nombre_servicio', sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint('id_categoria')
    )
    
    # <<< DATOS PARA LA TABLA CATEGORIA >>>
    categoria_table = sa.table('categoria',
        sa.column('id_categoria', sa.Integer),
        sa.column('nombre_categoria', sa.String),
        sa.column('nombre_servicio', sa.String)
    )
    op.bulk_insert(categoria_table,
        [
            {'id_categoria': 1, 'nombre_categoria': 'Tecnologia', 'nombre_servicio': 'Mantenimiento de pc Software'},
            {'id_categoria': 2, 'nombre_categoria': 'Tecnologia', 'nombre_servicio': 'Mantenimiento de pc hardware'}
        ]
    )

    op.create_table('rol',
        sa.Column('id_rol', sa.Integer(), nullable=False),
        sa.Column('rol', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('id_rol')
    )

    # <<< DATOS PARA LA TABLA ROL >>>
    rol_table = sa.table('rol',
        sa.column('id_rol', sa.Integer),
        sa.column('rol', sa.String)
    )
    op.bulk_insert(rol_table,
        [
            {'id_rol': 1, 'rol': 'Contratista'},
            {'id_rol': 2, 'rol': 'Prestador'}
        ]
    )

    op.create_table('mensajes',
        sa.Column('id_mensaje', sa.Integer(), nullable=False),
        sa.Column('mensajes', sa.String(length=500), nullable=True),
        sa.Column('id_categoria', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
        sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('usuario',
        sa.Column('cedula', sa.Integer(), nullable=False),
        sa.Column('nombres', sa.String(length=128), nullable=True),
        sa.Column('apellidos', sa.String(length=128), nullable=True),
        sa.Column('celular', sa.String(length=10), nullable=True),
        sa.Column('direccion', sa.String(length=300), nullable=True),
        sa.Column('contrasena_hash', sa.String(length=300), nullable=True),
        sa.Column('titulos_uni', sa.String(length=250), nullable=True),
        sa.Column('descripcion', sa.String(length=500), nullable=True),
        sa.Column('correo', sa.String(length=200), nullable=True),
        sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
        sa.Column('foto', sa.String(length=300), nullable=True),
        sa.Column('rol_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
        sa.PrimaryKeyConstraint('cedula')
    )
    op.create_table('portafolios',
        sa.Column('id_portafolio', sa.Integer(), nullable=False),
        sa.Column('descripcion', sa.String(length=128), nullable=True),
        sa.Column('imagenes', sa.String(length=500), nullable=True),
        sa.Column('usuario_cedula', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['usuario_cedula'], ['usuario.cedula'], ),
        sa.PrimaryKeyConstraint('id_portafolio')
    )
    op.create_table('postulacion_servicio',
        sa.Column('id_postulacion', sa.Integer(), nullable=False),
        sa.Column('descripcion', sa.String(length=500), nullable=True),
        sa.Column('whatsapp', sa.String(length=20), nullable=True),
        sa.Column('fecha_postulacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('usuario_cedula', sa.Integer(), nullable=False),
        sa.Column('categoria_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id_categoria'], ),
        sa.ForeignKeyConstraint(['usuario_cedula'], ['usuario.cedula'], ),
        sa.PrimaryKeyConstraint('id_postulacion')
    )
    op.create_table('reserva',
        sa.Column('id_reserva', sa.Integer(), nullable=False),
        sa.Column('fecha', sa.Date(), nullable=True),
        sa.Column('hora', sa.Time(), nullable=True),
        sa.Column('usuario_cedula', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['usuario_cedula'], ['usuario.cedula'], ),
        sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_table('usuario_calificacion',
        sa.Column('cedula', sa.Integer(), nullable=False),
        sa.Column('id_calificacion', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['cedula'], ['usuario.cedula'], ),
        sa.ForeignKeyConstraint(['id_calificacion'], ['calificacion.id_calificacion'], ),
        sa.PrimaryKeyConstraint('cedula', 'id_calificacion')
    )
    op.create_table('usuario_categoria',
        sa.Column('cedula', sa.Integer(), nullable=False),
        sa.Column('categoria_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id_categoria'], ),
        sa.ForeignKeyConstraint(['cedula'], ['usuario.cedula'], ),
        sa.PrimaryKeyConstraint('cedula', 'categoria_id')
    )
    op.create_table('estado_servicios',
        sa.Column('id_estado', sa.Integer(), nullable=False),
        sa.Column('estado_pago', sa.String(length=128), nullable=True),
        sa.Column('reporte', sa.String(length=128), nullable=True),
        sa.Column('estado_reserva', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['estado_reserva'], ['reserva.id_reserva'], ),
        sa.PrimaryKeyConstraint('id_estado'),
        sa.UniqueConstraint('estado_reserva')
    )
    op.create_table('historial',
        sa.Column('id_historial', sa.Integer(), nullable=False),
        sa.Column('reservas', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['reservas'], ['reserva.id_reserva'], ),
        sa.PrimaryKeyConstraint('id_historial'),
        sa.UniqueConstraint('reservas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    op.drop_table('estado_servicios')
    op.drop_table('usuario_categoria')
    op.drop_table('usuario_calificacion')
    op.drop_table('reserva')
    op.drop_table('postulacion_servicio')
    op.drop_table('portafolios')
    op.drop_table('usuario')
    op.drop_table('mensajes')
    op.drop_table('rol')
    op.drop_table('categoria')
    op.drop_table('calificacion')
    # ### end Alembic commands ###